image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(newversion)
  version_prefix: '{newversion}'
  package_version: $(newversion)
  assembly_version: $(newversion)
  file_version: $(newversion)
  informational_version: $(newversion)
  
environment:
  pfx_key:
    secure: dBFEXqEIAq2LjMxAIFMOg41T/9OZDNyfOupI1hnAlUe7yL4aB08MfQXvBlyMm6Ns
    
before_build:
  - nuget restore
  
install:
- ps: |
    $xmlPath = "$env:appveyor_build_folder\src\DynamicVML.csproj"
    $xml = [xml](get-content $xmlPath)
    $version = ($xml.Project.PropertyGroup | ? {$_.Version}).Version
    $env:newversion = ($version.Substring(0, $version.LastIndexOf(".") + 1)) + $env:appveyor_build_number
  
test:
  # only assemblies to test
  assemblies:
    only:
      - 'tests\**\tests.dll'
      
build:
  publish_nuget: false
  publish_nuget_symbols: true
  use_snupkg_format: true
  publish_aspnet_core: true
  verbosity: minimal